// 33_profanity.jsx: host side of "Sensor Kata Kasar" / "Bleep Profanity" (tool id profanity). ES3 only.
// Applies the engine plan {kind: "censor"} (engine/ac/tools/profanity.py) NON-DESTRUCTIVELY:
//   1. bac_profanity_begin  clone the source sequence as "<name> (Klipora)" (+ new audio track "Klipora Sensor")
//   2. bac_profanity_keys   volume keyframes with 10 ms ramps on the dialog clips of the CLONE (chunks of ranges)
//   3. bac_profanity_tones  beep / custom WAVs (generated by the engine) placed on the sensor track (chunks)
//   4. markers via the foundation bac_addMarkers(list, cloneId), tag "[Klipora-PF]" (old "[AC-PF]" still recognised)
// Verified helpers used (docs/research/premiere_timeline_api.md 5): Volume Level is linear, 1 = +15 dB
// (tlDbToLevel), key times are clip MEDIA time (tlSeqToMedia), QE addTracks appends an audio track
// (tlAddAudioTrack), overwriteClip(item, seconds) on an empty track never ripples. Never saves the project;
// imports only engine-made .wav files after File.exists (tlImportFile).

var PF_BIN = "Klipora";
var PF_EPS = 0.0005;

// Volume "Level" param of an audio TrackItem (stereo/mono/5.1 volume, never Channel Volume), or null.
function pfLevel(clip) {
    var comp = null, i;
    for (i = 0; i < clip.components.numItems; i++) {
        if (String(clip.components[i].matchName).indexOf("Internal Volume") === 0) { comp = clip.components[i]; break; }
    }
    if (!comp) {
        for (i = 0; i < clip.components.numItems; i++) {
            if (clip.components[i].displayName === "Volume") { comp = clip.components[i]; break; }
        }
    }
    if (!comp) return null;
    return tlProp(comp, "Level") || (comp.properties.numItems > 1 ? comp.properties[1] : null);   // [0] Bypass [1] Level
}

function pfKeySec(k) { return (typeof k === "number") ? k : Number(k.seconds); }

// Remove existing Level keys strictly inside (m0, m1) (media seconds) so our ramp is not bent by old keys.
function pfRemoveKeys(lvl, m0, m1) {
    var keys = lvl.getKeys(), n = 0;
    if (!keys) return 0;
    for (var i = keys.length - 1; i >= 0; i--) {
        var s = pfKeySec(keys[i]);
        if (s > m0 + 1e-6 && s < m1 - 1e-6) {
            try { lvl.removeKey(keys[i]); n++; } catch (e) { /* key vanished */ }
        }
    }
    return n;
}

// Key one clip for the censor range [a, b) (sequence seconds): base -> low over `ramp`, low, low -> base.
// factor = linear gain inside (0 = mute, 0.1 = -20 dB duck). Keys are clamped to the clip; a range that runs
// past a clip edge keeps the level low up to that edge (the next clip gets its own keys).
function pfKeyClip(clip, a, b, factor, ramp, last) {
    var lvl = pfLevel(clip);
    if (!lvl) return 0;
    var s = clip.start.seconds, e = clip.end.seconds;
    var a2 = Math.max(a, s), b2 = Math.min(b, e);
    if (b2 - a2 <= PF_EPS) return 0;
    var pre = Math.max(s, a - ramp), post = Math.min(e, b + ramp), pts = [];
    var varying = lvl.isTimeVarying();
    // Old keys inside the window go FIRST, so the base level is read from the curve around the range (reading it
    // with an earlier mute key still in place gave 0 and turned a re-run "Kecilkan" into a mute; verified live).
    if (varying) {
        pfRemoveKeys(lvl, tlSeqToMedia(clip, pre), tlSeqToMedia(clip, post));
        var left = lvl.getKeys();
        if (!left || !left.length) { lvl.setTimeVarying(false); varying = false; }
    }
    var stat = varying ? 0 : Number(lvl.getValue());
    var base = function (t) { return varying ? Number(lvl.getValueAtTime(tlSeqToMedia(clip, t))) : stat; };
    if (a > s + PF_EPS) pts.push([pre, base(pre)]);
    pts.push([a2, factor > 0 ? base(a2) * factor : 0]);
    pts.push([b2, factor > 0 ? base(b2) * factor : 0]);
    if (b < e - PF_EPS) pts.push([post, base(post)]);
    if (!varying) lvl.setTimeVarying(true);
    for (var i = 0; i < pts.length; i++) {
        var mt = tlSeqToMedia(clip, pts[i][0]), ui = !!last && i === pts.length - 1;
        lvl.addKey(mt);
        lvl.setValueAtKey(mt, pts[i][1], ui);
        try { lvl.setInterpolationTypeAtKey(mt, TL_INTERP.LINEAR, ui); } catch (e1) { /* audio keys are linear by default */ }
    }
    return pts.length;
}

// Rename audio track idx of seq (the official Track.name may be read-only: fall back to QE setName).
// UNVERIFIED on 26.2.2: the verifier checks the track label in the timeline.
function pfNameTrack(seq, idx, name) {
    try { seq.audioTracks[idx].name = name; } catch (e1) { /* read-only */ }
    if (String(seq.audioTracks[idx].name) === name) return true;
    try {
        app.enableQE();
        var qt = qe.project.getActiveSequence().getAudioTrackAt(idx);
        if (qt && typeof qt.setName === "function") qt.setName(name);
    } catch (e2) { /* QE without setName */ }
    return String(seq.audioTracks[idx].name) === name;
}

// Remove the Level keys of an earlier sensor run in the media window of [t0, t1] (sequence seconds) on one clip.
// When no key is left, the level goes back to static at the level the old keys returned to. Returns keys removed.
function pfDropKeys(clip, lvl, t0, t1, a, b) {
    var m0 = tlSeqToMedia(clip, t0) - 1e-6, m1 = tlSeqToMedia(clip, t1) + 1e-6;
    var ma = tlSeqToMedia(clip, a), mb = tlSeqToMedia(clip, b), keys = lvl.getKeys(), kill = [], base = null, i;
    if (!keys) return 0;
    for (i = 0; i < keys.length; i++) {
        var s = pfKeySec(keys[i]);
        if (s < m0 || s > m1) continue;
        kill.push(keys[i]);
        if (base === null && (s < ma - 1e-4 || s > mb + 1e-4)) base = Number(lvl.getValueAtKey(keys[i]));   // ramp end = old base
    }
    for (i = kill.length - 1; i >= 0; i--) { try { lvl.removeKey(kill[i]); } catch (e) { /* key vanished */ } }
    var left = lvl.getKeys();
    if (kill.length && (!left || !left.length)) {
        lvl.setTimeVarying(false);
        if (base !== null) lvl.setValue(base, false);
    }
    return kill.length;
}

// A re-run on a sequence that was already censored (the clone of a clone) REPLACES the old sensor instead of
// stacking a second one: the old [Klipora-PF] / [AC-PF] markers say where it was; our Level keys around those ranges are removed,
// clips on the old sensor track(s) ("Klipora Sensor" or the old "AutoCut Sensor") are cleared and the old markers deleted. Only touches the new clone.
// Returns {ranges, keys, clips, tracks: [indexes of tracks named trackName]}.
function pfUndoOld(seq, trackName, tag) {
    var out = { ranges: 0, keys: 0, clips: 0, tracks: [] }, old = [], sensor = {}, i, ti, ci;
    try {
        var mk = seq.markers, m = mk.getFirstMarker(), kill = [], guard = 0;
        while (m && guard++ < 100000) {
            if (acHasTag(m.comments, tag) || acHasTag(m.name, tag)) {
                old.push([m.start.seconds, m.end.seconds]);
                kill.push(m);
            }
            m = mk.getNextMarker(m);
        }
        for (i = 0; i < kill.length; i++) mk.deleteMarker(kill[i]);
    } catch (e1) { /* sequence without a markers API */ }
    out.ranges = old.length;
    for (ti = 0; ti < seq.audioTracks.numTracks; ti++) {
        var tr = seq.audioTracks[ti];
        if (!trackName || !acNameIs(tr.name, trackName)) continue;
        out.tracks.push(ti);
        sensor[ti] = 1;
        while (tr.clips.numItems > 0) { tr.clips[0].remove(false, true); out.clips++; }
    }
    if (!old.length) return out;
    var w = Math.max(0.01, 1 / tlFps(seq)) + 0.002;          // the old ramp (max(10 ms, 1 frame)) + slack
    for (ti = 0; ti < seq.audioTracks.numTracks; ti++) {
        if (sensor[ti] || seq.audioTracks[ti].isLocked()) continue;
        var clips = seq.audioTracks[ti].clips;
        for (ci = 0; ci < clips.numItems; ci++) {
            var c = clips[ci], s = c.start.seconds, e = c.end.seconds, lvl = null;
            for (i = 0; i < old.length; i++) {
                if (old[i][1] + w <= s || old[i][0] - w >= e) continue;
                if (lvl === null) lvl = pfLevel(c) || false;
                if (lvl && lvl.isTimeVarying()) out.keys += pfDropKeys(c, lvl, old[i][0] - w, old[i][1] + w, old[i][0], old[i][1]);
            }
        }
    }
    return out;
}

// Clone the source sequence and prepare the sensor track. opts {track: bool (a sound is placed; default true
// when trackName is set), tag ("[Klipora-PF]")}. An earlier sensor on the source is undone in the clone (pfUndoOld) and
// its sensor track is reused. Returns {ok, id, name, origId, origName, track, named, trackName, undo}. On any
// failure after cloning, the half-made clone is deleted again (it is ours).
function bac_profanity_begin(srcId, name, trackName, opts) {
    var c = null;
    try {
        opts = opts || {};
        var src = acSeq(srcId);
        if (!src) return acErr(acT("profanitySrcGone", "Sequence yang dicari tadi tidak ditemukan. Buka lagi lalu ulangi."));
        c = tlCloneSequence(src, acUniqueSeqName(name || (src.name + AC_SEQ_SUFFIX)), null);
        if (!c) return acErr(acT("profanityCloneFail", "Gagal menggandakan sequence."));
        acMarkMade(c);
        app.project.openSequence(c.sequenceID);
        var undo = pfUndoOld(c, trackName || "", opts.tag || "[Klipora-PF]");
        var want = !!trackName && (opts.track === undefined || opts.track === null || !!opts.track);
        var idx = undo.tracks.length ? undo.tracks[0] : -1, named = idx >= 0;
        if (want && idx < 0) {
            var tr = tlAddAudioTrack(c);
            if (!tr) { app.project.deleteSequence(c); return acErr(acT("profanityTrackFail", "Gagal menambah track audio untuk nada sensor.")); }
            idx = c.audioTracks.numTracks - 1;
            named = pfNameTrack(c, idx, trackName);
        }
        return acOk({ ok: true, id: c.sequenceID, name: c.name, origId: src.sequenceID, origName: src.name,
                      track: idx, named: named, trackName: idx >= 0 ? String(c.audioTracks[idx].name) : "",
                      undo: { ranges: undo.ranges, keys: undo.keys, clips: undo.clips } });
    } catch (e) {
        try { if (c) app.project.deleteSequence(c); } catch (e2) { /* already gone */ }
        return acCatch(e, "bac_profanity_begin");
    }
}

// ranges: [{t0, t1, paths: [media paths]}] (sequence seconds). Only clips whose media is in `paths` are keyed
// (dialog only: music on other tracks keeps playing). Locked tracks and disabled clips are skipped (reported).
// opts: {mode: "mute"|"beep"|"custom"|"duck", duckDb, ramp, skipTrack, last}. The ramp is at least one frame,
// so ramp keys never share a frame if Premiere snaps keys (UNVERIFIED below 120 fps).
// Returns {ok, keys, clips, missed: [range indexes without a matching clip], locked: [track names], ms}.
function bac_profanity_keys(seqId, ranges, opts) {
    try {
        var seq = tlSeqById(String(seqId));
        if (!seq) return acErr(acT("profanityNoResult", "Sequence hasil tidak ditemukan."));
        opts = opts || {};
        var t0 = new Date().getTime(), ramp = Math.max(Number(opts.ramp) || 0.01, 1 / tlFps(seq));
        var factor = opts.mode === "duck" ? Math.pow(10, (Number(opts.duckDb) || -20) / 20) : 0;
        var skip = (opts.skipTrack === undefined || opts.skipTrack === null) ? -1 : Number(opts.skipTrack);
        // Read every clip once (COM property reads are the slow part of ExtendScript).
        var all = [], locked = [], ti, ci;
        for (ti = 0; ti < seq.audioTracks.numTracks; ti++) {
            if (ti === skip) continue;
            var track = seq.audioTracks[ti], clips = track.clips;
            if (track.isLocked()) { if (clips.numItems) locked.push(String(track.name || ("A" + (ti + 1)))); continue; }
            for (ci = 0; ci < clips.numItems; ci++) {
                var c = clips[ci], pi = c.projectItem;
                if (c.disabled) continue;
                all.push({ c: c, s: c.start.seconds, e: c.end.seconds, p: pi ? tlNormPath(pi.getMediaPath() || "") : "" });
            }
        }
        var keys = 0, nClips = 0, missed = [];
        for (var r = 0; r < ranges.length; r++) {
            var a = Number(ranges[r].t0), b = Number(ranges[r].t1), want = {}, any = false, hit = 0, k;
            var paths = ranges[r].paths || [];
            for (k = 0; k < paths.length; k++) { want[tlNormPath(paths[k])] = 1; any = true; }
            for (k = 0; k < all.length; k++) {
                var x = all[k];
                if (x.e <= a || x.s >= b || !x.p) continue;
                if (any && !want[x.p]) continue;
                var n = pfKeyClip(x.c, a, b, factor, ramp, opts.last && r === ranges.length - 1);
                if (n > 0) { keys += n; nClips++; hit++; }
            }
            if (!hit) missed.push(r);
        }
        return acOk({ ok: true, keys: keys, clips: nClips, missed: missed, locked: locked, ramp: ramp,
                      ms: new Date().getTime() - t0 });
    } catch (e) { return acCatch(e, "bac_profanity_keys"); }
}

// tones: [{t: start seconds, path: engine-made .wav}] placed with overwriteClip on audio track trackIdx.
// Each WAV is imported once into bin "Klipora" (old "AutoCut BOT" reused) (reused on re-runs). Returns {ok, placed, missing, ms}.
function bac_profanity_tones(seqId, trackIdx, tones) {
    try {
        var seq = tlSeqById(String(seqId));
        if (!seq) return acErr(acT("profanityNoResult", "Sequence hasil tidak ditemukan."));
        var tr = seq.audioTracks[Number(trackIdx)];
        if (!tr) return acErr(acT("profanityNoTrack", "Track sensor tidak ditemukan."));
        var t0 = new Date().getTime(), bin = tlFindBin(PF_BIN, true), cache = {}, placed = 0, missing = [];
        for (var i = 0; i < tones.length; i++) {
            var p = String(tones[i].path || "");
            if (!/\.wav$/i.test(p)) { missing.push(p); continue; }         // only WAVs the engine generated
            var item = cache[p];
            if (item === undefined) { item = tlImportFile(p, bin); cache[p] = item; }   // File.exists first: no modal
            if (!item) { missing.push(p); continue; }
            tr.overwriteClip(item, Number(tones[i].t));
            placed++;
        }
        return acOk({ ok: true, placed: placed, missing: missing, ms: new Date().getTime() - t0 });
    } catch (e) { return acCatch(e, "bac_profanity_tones"); }
}

// Read-back for the verifier and the result card: Level in dB of every audio clip under each time (sequence
// seconds) plus the clips on track `trackIdx`. Returns {ok, at: [{t, levels: [{track, db}]}], tones: [[s, e, name]]}.
function bac_profanity_probe(seqId, times, trackIdx) {
    try {
        var seq = acSeq(seqId);
        if (!seq) return acErr(acT("profanityNoSeq", "Sequence tidak ditemukan."));
        var out = [], i, ti, ci;
        for (i = 0; i < times.length; i++) {
            var t = Number(times[i]), lv = [];
            for (ti = 0; ti < seq.audioTracks.numTracks; ti++) {
                var clips = seq.audioTracks[ti].clips;
                for (ci = 0; ci < clips.numItems; ci++) {
                    var c = clips[ci];
                    if (c.start.seconds > t || c.end.seconds <= t) continue;
                    var lvl = pfLevel(c);
                    if (!lvl) continue;
                    var v = lvl.isTimeVarying() ? lvl.getValueAtTime(tlSeqToMedia(c, t)) : lvl.getValue();
                    lv.push({ track: ti, db: Number(v) > 0 ? Math.round(tlLevelToDb(Number(v)) * 10) / 10 : -999,
                              keys: lvl.isTimeVarying() ? lvl.getKeys().length : 0 });
                }
            }
            out.push({ t: t, levels: lv });
        }
        var tones = [];
        if (trackIdx !== undefined && trackIdx !== null && seq.audioTracks[Number(trackIdx)]) {
            var tc = seq.audioTracks[Number(trackIdx)].clips;
            for (ci = 0; ci < tc.numItems; ci++) tones.push([tc[ci].start.seconds, tc[ci].end.seconds, tc[ci].name]);
        }
        return acOk({ ok: true, at: out, tones: tones, nAudio: seq.audioTracks.numTracks });
    } catch (e) { return acCatch(e, "bac_profanity_probe"); }
}
