"""ac.transcript: pure post-processing rules + the v3 / listener caches of the test media (no GPU by default).
  python engine/tests/test_transcript.py          offline checks (cached transcripts)
  python engine/tests/test_transcript.py --gpu    also re-transcribe a COPY of the 49 s file (GPU lock)"""
import re
import shutil
import time

import numpy as np

import _common
from _common import MEDIA_2M, MEDIA_34M, MEDIA_49


from ac import transcript as T

# ---- continuation merge
rows = [[" Baik,", 2.2, 2.8, 0, 0.9], [" teman", 3.0, 3.3, 0, 0.8], ["-teman", 3.3, 3.5, 1, 0.95],
        [" warungku", 4.0, 4.5, 0, 0.9], [".com", 4.5, 4.7, 0, 0.6], [" Rp1", 5, 5.2, 0, 0.9], [".000", 5.2, 5.5, 1, 0.9],
        ["Halo", 6, 6.3, 0, 0.9], [" 50", 7, 7.2, 0, 0.9], ["%", 7.2, 7.3, 1, 0.9]]
m = T.merge_continuations([list(r) for r in rows])
assert [r[0] for r in m] == [" Baik,", " teman-teman", " warungku.com", " Rp1.000", " Halo", " 50%"], m
assert m[1][1:4] == [3.0, 3.5, 1] and m[2][4] == 0.6
assert all(r[0].startswith(" ") for r in m)


# ---- hallucination filter
def W(text, t0, seg=0, dt=0.4):
    return [" " + text, t0, t0 + dt, seg, 0.9]


seq = [W("Oke", 0), W("kita", 0.4), W("mulai", 0.8, 1),
       W("Terima", 2), W("kasih", 2.4), W("telah", 2.8), W("menonton.", 3.2, 1),
       W("Terima", 5), W("kasih", 5.4), W("telah", 5.8), W("menonton.", 6.2, 1),
       W("Tenggak", 8), W("Tenggak", 8.4), W("Tenggak", 8.8), W("Tenggak", 9.2, 1),
       W("eh", 10), W("sorry", 10.4), W("sorry", 10.8), W("sorry", 11.2, 1),
       W("ya", 12), W("ya", 12.4), W("ya", 12.8), W("oke", 13.2, 1),
       W("Rp1.000", 14), W("Rp1.000", 14.4), W("eh", 14.8), W("Rp1.000", 15.2), W("nah", 15.6), W("Rp1.000", 16, 1),
       W("selamat", 18), W("menikmati", 18.4, 1)]
clean, issues = T.drop_hallucinations([list(r) for r in seq])
text = T.text_of(clean)
assert "menonton" not in text and "Tenggak" not in text and "menikmati" not in text, text
assert "sorry sorry sorry" in text and "ya ya ya oke" in text and text.count("Rp1.000") == 4, text
kinds = {i["kind"] for i in issues}
assert "phrase" in kinds and kinds & {"loop", "segloop"}, issues
# a single outro phrase spoken over clear sound is kept (speaker really said it), over silence it is dropped
outro = [W("Oke", 0), W("sampai", 0.4), W("jumpa", 0.8), W("di", 1.2), W("video", 1.6), W("selanjutnya.", 2.0, 1)]
loud = np.ones(400, bool)
quiet = np.zeros(400, bool)
assert len(T.drop_hallucinations([list(r) for r in outro], on=loud)[0]) == 6
assert T.text_of(T.drop_hallucinations([list(r) for r in outro], on=quiet)[0]) == "Oke"

# ---- de-stretch: word starting 0.6 s before its sound moves to the onset (minus 30 ms); end kept
on = np.zeros(500, bool)
on[150:200] = True          # sound 1.50-2.00 s
r2, moved = T.destretch([[" Kamu", 0.9, 2.0, 0, 0.9], [" lagi", 1.6, 1.9, 0, 0.9], [" sepi", 3.0, 3.5, 0, 0.9]], on)
assert moved == 1 and r2[0][1] == 1.47 and r2[0][2] == 2.0, r2
assert r2[1][1] == 1.6 and r2[2][1] == 3.0          # already sounding / no sound inside: untouched

# ---- hole finder: voiced 1.0-4.0 s with no words -> one span; covered speech -> none
on = np.zeros(1000, bool)
on[100:400] = True
on[600:700] = True
holes = T.find_holes([[" kata", 6.0, 7.0, 1, 0.9]], on)
assert holes == [[1.0, 4.0, 3.0]], holes
assert T.find_holes([[" a", 0.9, 4.2, 1, 0.9], [" b", 6.0, 7.0, 1, 0.9]], on) == []

# ---- caches of the test media (regenerated by the foundation agent; no GPU here)
report = []
for media in (MEDIA_49, MEDIA_2M, MEDIA_34M):
    if not media.is_file():
        print("SKIP", media)
        continue
    doc = T.load_doc(media)
    assert doc and doc["v"] == 3 and doc["model"] == "large-v3-turbo" and doc["lang"] == "id", media
    w = doc["words"]
    assert w and all(len(r) == 5 for r in w)
    assert all(r[2] > r[1] for r in w), "zero/negative length word"
    assert all(b[1] >= a[1] for a, b in zip(w, w[1:])), "not sorted"
    assert all(b[1] >= a[2] - 1e-6 for a, b in zip(w, w[1:])), "overlapping words"
    # every row is a whole word (" .com" with a space is a spoken "titik com" and stays its own word)
    assert all(r[0].startswith(" ") and not re.match(r"^ [-%]", r[0]) for r in w), "unmerged continuation"
    assert not re.search(r"terima kasih telah menonton", T.text_of(w), re.I)
    lw = T.listener_words(media)        # cached: must not need the GPU
    assert lw and all(len(r) == 4 for r in lw)
    report.append(f"{media.name}: {len(w)} words, {doc['secs']} s, moved {doc['destretch']['moved']}, "
                  f"holes checked {doc['repair']['checked']} added {doc['repair']['added']}, listener {len(lw)}")
    if media == MEDIA_34M:
        hole = [r for r in w if 94.0 <= r[1] <= 113.0]
        assert len(hole) >= 30, f"94-113 s hole not filled: {len(hole)} words"
        assert any("teman-teman" in r[0] for r in w)
    t0 = time.time()
    assert T.words(media) == w and time.time() - t0 < 1.0     # served from cache

# ---- optional live GPU run on a copy (never touches the originals)
if _common.flag("--gpu") and MEDIA_49.is_file():
    tmp = _common.scratch("transcript")
    cp = tmp / "a49.mp4"
    shutil.copy2(MEDIA_49, cp)
    t0 = time.time()
    w = T.words(cp, refresh=True)
    secs = time.time() - t0
    assert 60 < len(w) < 120, len(w)
    assert T.load_doc(cp)["device"] in ("cuda", "cpu")
    report.append(f"GPU run on 49 s copy: {len(w)} words in {secs:.1f} s")
    # v2 cache (engine/caption.py era) is upgraded in place: post-processing + hole repair, no full pass
    v2 = _common.ROOT / "proto" / "ai" / "data" / "legacy_v2_words.json"
    if v2.is_file():
        shutil.copy2(v2, T.words_path(cp))
        t0 = time.time()
        w2 = T.words(cp)
        doc = T.load_doc(cp)
        assert doc["upgraded_from"] == 2 and doc["v"] == 3 and all(r[4] == 1.0 for r in w2)
        report.append(f"v2 -> v3 upgrade: {len(w2)} words in {time.time() - t0:.1f} s")
    T.unload_models()
    _common.cleanup("transcript")

print("\n".join(report))
print("ok")
